// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251017095514_FixData")]
    partial class FixData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Budget.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Alimentation et Boissons"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Auto et Transports"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Besoins essentiels"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Dépenses professionnelles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Divers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Espèces et Chèques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Factures et Service"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Frais"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Impôts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Investissements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Loisirs et Divertissements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Remboursement emprunt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Remboursements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Revenus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Santé"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Virements"
                        });
                });

            modelBuilder.Entity("Api.Models.Budget.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NULL");

                    b.HasIndex("Name", "CategoryId", "UserId")
                        .IsUnique();

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Bars"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Cafés"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Courses"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Abonnement"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Abonnement"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Location de voiture"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Lavage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Carburant"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Assurance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Parking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Billets d'avion"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Transports publics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Réparations"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Taxis, VTC et Covoiturage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Péages"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Billets de train"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Garde d'enfants"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000021"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Vêtements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000022"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Éducation"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000023"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Soins personnels"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000024"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Cadeaux"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000025"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Animaux de compagnie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000026"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Loyer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000027"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Fournitures ménagères"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000028"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Frais de scolarité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000029"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Comptabilité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000030"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Publicité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000031"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Voyages d'affaires"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000032"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Conseil financier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000033"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Freelancing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000034"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Assistance juridique"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000035"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000036"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Fournitures de bureau"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000037"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Service en ligne"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000038"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Impressions"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000039"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Services professionnels"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000040"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Salaire"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000041"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Frais d'envois"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000042"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Achat divers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000043"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "I don't know"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000044"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Dépôts en espèces"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000045"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Dépôts de chèques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000046"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Retraits"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000047"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Autres abonnements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000048"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Électricité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000049"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Chauffage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000050"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Internet"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000051"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Téléphone portable"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000052"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Déchets et Recyclage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000053"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Eau"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000054"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Frais bancaires"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000055"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Frais de retard"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000056"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Frais de service"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000057"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Impôts sur les sociétés"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000058"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Impôts sur les plus-values"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000059"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Impôts sur le revenu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000060"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Impôts fonciers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000061"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Cotisations sociales"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000062"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "TVA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000063"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Obligations"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000064"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Crowdfunding"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000065"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Cryptos"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000066"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Immobilier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000067"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Retraite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000068"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Épargne de sécurité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000069"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Actions"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000070"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "ETF"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000071"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Private Equity"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000072"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Art et Musées"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000073"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Film"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000074"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Livre"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000075"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000076"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Jeux"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000077"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Cinéma et Théâtre"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000078"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Activité"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000079"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000080"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Abonnements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000081"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Vacances"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000082"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Boîte de nuit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000083"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Festival"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000084"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Résidence principale"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000085"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Crédit auto"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000086"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Paiements d'assurances"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000087"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Retours produits"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000088"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Remboursements d'impôts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000089"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Réclamation et Garanties"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000090"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Remboursement proche"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000091"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Bonus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000092"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Cadeaux"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000093"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Investissements"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000094"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Revenus locatifs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000095"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Salaire"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000096"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Dentiste"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000097"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Médecin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000098"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Assurance maladie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000099"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Matériel médical"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000100"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Médicaments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000101"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Opticien"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000102"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Dermatologue"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000103"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Paiement des factures"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000104"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Transferts externes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000105"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Dons"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000106"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Transferts internes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000107"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Transferts internationaux"
                        });
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Api.Models.Budget.SubCategory", b =>
                {
                    b.HasOne("Api.Models.Budget.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Models.Budget.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
